POST http://localhost:8080/user
Content-Type: application/json

{
    "username": "Mugammad",
    "email": "mobread@gmail.com",
    "password": "password"
}

####

GET http://localhost:8080/user

###

POST http://localhost:8080/signin
Content-Type: application/json

{
    "email": "mobread@gmail.com",
    "password": "passwor"
}